name: Build project

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        working-directory: ${{github.workspace}}/bin
        run: ./tests
