name: Build project

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CXX: g++-10
      CC: gcc-10

    steps:
      - uses: actions/checkout@v3
      - name: Install CGAL
        run: sudo apt install -y libcgal-dev
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        working-directory: ${{github.workspace}}/bin
        run: ./tests
